// flow-typed signature: d53e55553ec9aefd48fc416213f52dd1
// flow-typed version: <<STUB>>/react-router-dynamic-breadcrumbs_v^2.2.0/flow_v0.111.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-dynamic-breadcrumbs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-dynamic-breadcrumbs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router-dynamic-breadcrumbs/dist/Breadcrumbs' {
  declare module.exports: any;
}

declare module 'react-router-dynamic-breadcrumbs/dist/BreadcrumbsItem' {
  declare module.exports: any;
}

declare module 'react-router-dynamic-breadcrumbs/dist/index' {
  declare module.exports: any;
}

declare module 'react-router-dynamic-breadcrumbs/src/Breadcrumbs' {
  declare module.exports: any;
}

declare module 'react-router-dynamic-breadcrumbs/src/BreadcrumbsItem' {
  declare module.exports: any;
}

declare module 'react-router-dynamic-breadcrumbs/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router-dynamic-breadcrumbs/dist/Breadcrumbs.js' {
  declare module.exports: $Exports<'react-router-dynamic-breadcrumbs/dist/Breadcrumbs'>;
}
declare module 'react-router-dynamic-breadcrumbs/dist/BreadcrumbsItem.js' {
  declare module.exports: $Exports<'react-router-dynamic-breadcrumbs/dist/BreadcrumbsItem'>;
}
declare module 'react-router-dynamic-breadcrumbs/dist/index.js' {
  declare module.exports: $Exports<'react-router-dynamic-breadcrumbs/dist/index'>;
}
declare module 'react-router-dynamic-breadcrumbs/src/Breadcrumbs.js' {
  declare module.exports: $Exports<'react-router-dynamic-breadcrumbs/src/Breadcrumbs'>;
}
declare module 'react-router-dynamic-breadcrumbs/src/BreadcrumbsItem.js' {
  declare module.exports: $Exports<'react-router-dynamic-breadcrumbs/src/BreadcrumbsItem'>;
}
declare module 'react-router-dynamic-breadcrumbs/src/index.js' {
  declare module.exports: $Exports<'react-router-dynamic-breadcrumbs/src/index'>;
}
