stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build --target builder -t internal-portal-front-builder -f ci_cd/docker/Dockerfile .
    - docker build --target web -t $CI_REGISTRY/$CI_PROJECT_PATH:latest -f ci_cd/docker/Dockerfile .
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:latest
    - docker rmi $CI_REGISTRY/$CI_PROJECT_PATH:latest
  tags:
    - build
  only:
    - develop

deploy:
  stage: deploy
  script:
    - cd ci_cd/ansible && ansible-playbook books/deploy.yml -i inventories/develop -e docker_registry=$CI_REGISTRY -e docker_login="gitlab-ci-token" -e docker_pass=$CI_JOB_TOKEN -e docker_image=$CI_REGISTRY/$CI_PROJECT_PATH:latest
  tags:
    - deploy
  only:
    - develop

