// flow-typed signature: 4794861eb84257d6c1d0b0cdb89945ec
// flow-typed version: <<STUB>>/apollo-boost_v0.4.4/flow_v0.107.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-boost'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-boost' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-boost/lib/bundle.cjs' {
  declare module.exports: any;
}

declare module 'apollo-boost/lib/bundle.cjs.min' {
  declare module.exports: any;
}

declare module 'apollo-boost/lib/bundle.esm' {
  declare module.exports: any;
}

declare module 'apollo-boost/lib/bundle.umd' {
  declare module.exports: any;
}

declare module 'apollo-boost/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-boost/lib/bundle.cjs.js' {
  declare module.exports: $Exports<'apollo-boost/lib/bundle.cjs'>;
}
declare module 'apollo-boost/lib/bundle.cjs.min.js' {
  declare module.exports: $Exports<'apollo-boost/lib/bundle.cjs.min'>;
}
declare module 'apollo-boost/lib/bundle.esm.js' {
  declare module.exports: $Exports<'apollo-boost/lib/bundle.esm'>;
}
declare module 'apollo-boost/lib/bundle.umd.js' {
  declare module.exports: $Exports<'apollo-boost/lib/bundle.umd'>;
}
declare module 'apollo-boost/lib/index.js' {
  declare module.exports: $Exports<'apollo-boost/lib/index'>;
}
