// flow-typed signature: 059e6fd922fe139b180c532b64113eaf
// flow-typed version: <<STUB>>/okami_v0.2.5/flow_v0.107.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'okami'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'okami' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'okami/dist/okami.cjs' {
  declare module.exports: any;
}

declare module 'okami/dist/okami.esm' {
  declare module.exports: any;
}

declare module 'okami/dist/okami.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'okami/dist/okami.cjs.js' {
  declare module.exports: $Exports<'okami/dist/okami.cjs'>;
}
declare module 'okami/dist/okami.esm.js' {
  declare module.exports: $Exports<'okami/dist/okami.esm'>;
}
declare module 'okami/dist/okami.umd.js' {
  declare module.exports: $Exports<'okami/dist/okami.umd'>;
}
