// flow-typed signature: 615919d285cd7c6d8f51414bc3482350
// flow-typed version: <<STUB>>/react-moment_v0.9.6/flow_v0.107.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-moment'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-moment' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-moment/coverage/lcov-report/block-navigation' {
  declare module.exports: any;
}

declare module 'react-moment/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'react-moment/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'react-moment/dist/index' {
  declare module.exports: any;
}

declare module 'react-moment/src/index' {
  declare module.exports: any;
}

declare module 'react-moment/src/objects' {
  declare module.exports: any;
}

declare module 'react-moment/tests/index' {
  declare module.exports: any;
}

declare module 'react-moment/tests/objects' {
  declare module.exports: any;
}

declare module 'react-moment/tests/ssr/app' {
  declare module.exports: any;
}

declare module 'react-moment/tests/ssr/index' {
  declare module.exports: any;
}

declare module 'react-moment/tests/ssr/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-moment/coverage/lcov-report/block-navigation.js' {
  declare module.exports: $Exports<'react-moment/coverage/lcov-report/block-navigation'>;
}
declare module 'react-moment/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'react-moment/coverage/lcov-report/prettify'>;
}
declare module 'react-moment/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'react-moment/coverage/lcov-report/sorter'>;
}
declare module 'react-moment/dist/index.js' {
  declare module.exports: $Exports<'react-moment/dist/index'>;
}
declare module 'react-moment/src/index.jsx' {
  declare module.exports: $Exports<'react-moment/src/index'>;
}
declare module 'react-moment/src/objects.js' {
  declare module.exports: $Exports<'react-moment/src/objects'>;
}
declare module 'react-moment/tests/index.jsx' {
  declare module.exports: $Exports<'react-moment/tests/index'>;
}
declare module 'react-moment/tests/objects.js' {
  declare module.exports: $Exports<'react-moment/tests/objects'>;
}
declare module 'react-moment/tests/ssr/app.jsx' {
  declare module.exports: $Exports<'react-moment/tests/ssr/app'>;
}
declare module 'react-moment/tests/ssr/index.js' {
  declare module.exports: $Exports<'react-moment/tests/ssr/index'>;
}
declare module 'react-moment/tests/ssr/server.js' {
  declare module.exports: $Exports<'react-moment/tests/ssr/server'>;
}
