// flow-typed signature: 2dff8325834026a0c9b71e39196e3322
// flow-typed version: <<STUB>>/react-table_v^7.0.0-beta.12/flow_v0.107.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-table'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-table' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-table/dist/index.es' {
  declare module.exports: any;
}

declare module 'react-table/dist/index' {
  declare module.exports: any;
}

declare module 'react-table/src/actions' {
  declare module.exports: any;
}

declare module 'react-table/src/aggregations' {
  declare module.exports: any;
}

declare module 'react-table/src/filterTypes' {
  declare module.exports: any;
}

declare module 'react-table/src/hooks/tests/useTable.test' {
  declare module.exports: any;
}

declare module 'react-table/src/hooks/useTable' {
  declare module.exports: any;
}

declare module 'react-table/src/index' {
  declare module.exports: any;
}

declare module 'react-table/src/plugin-hooks/tests/useAbsoluteLayout.test' {
  declare module.exports: any;
}

declare module 'react-table/src/plugin-hooks/tests/useBlockLayout.test' {
  declare module.exports: any;
}

declare module 'react-table/src/plugin-hooks/tests/useExpanded.test' {
  declare module.exports: any;
}

declare module 'react-table/src/plugin-hooks/tests/useFilters.test' {
  declare module.exports: any;
}

declare module 'react-table/src/plugin-hooks/tests/useGroupBy.test' {
  declare module.exports: any;
}

declare module 'react-table/src/plugin-hooks/tests/usePagination.test' {
  declare module.exports: any;
}

declare module 'react-table/src/plugin-hooks/tests/useRowSelect.test' {
  declare module.exports: any;
}

declare module 'react-table/src/plugin-hooks/tests/useSortBy.test' {
  declare module.exports: any;
}

declare module 'react-table/src/plugin-hooks/useAbsoluteLayout' {
  declare module.exports: any;
}

declare module 'react-table/src/plugin-hooks/useBlockLayout' {
  declare module.exports: any;
}

declare module 'react-table/src/plugin-hooks/useColumnOrder' {
  declare module.exports: any;
}

declare module 'react-table/src/plugin-hooks/useExpanded' {
  declare module.exports: any;
}

declare module 'react-table/src/plugin-hooks/useFilters' {
  declare module.exports: any;
}

declare module 'react-table/src/plugin-hooks/useGroupBy' {
  declare module.exports: any;
}

declare module 'react-table/src/plugin-hooks/usePagination' {
  declare module.exports: any;
}

declare module 'react-table/src/plugin-hooks/useResizeColumns' {
  declare module.exports: any;
}

declare module 'react-table/src/plugin-hooks/useRowSelect' {
  declare module.exports: any;
}

declare module 'react-table/src/plugin-hooks/useRowState' {
  declare module.exports: any;
}

declare module 'react-table/src/plugin-hooks/useSortBy' {
  declare module.exports: any;
}

declare module 'react-table/src/sortTypes' {
  declare module.exports: any;
}

declare module 'react-table/src/utility-hooks/useTokenPagination' {
  declare module.exports: any;
}

declare module 'react-table/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-table/dist/index.es.js' {
  declare module.exports: $Exports<'react-table/dist/index.es'>;
}
declare module 'react-table/dist/index.js' {
  declare module.exports: $Exports<'react-table/dist/index'>;
}
declare module 'react-table/src/actions.js' {
  declare module.exports: $Exports<'react-table/src/actions'>;
}
declare module 'react-table/src/aggregations.js' {
  declare module.exports: $Exports<'react-table/src/aggregations'>;
}
declare module 'react-table/src/filterTypes.js' {
  declare module.exports: $Exports<'react-table/src/filterTypes'>;
}
declare module 'react-table/src/hooks/tests/useTable.test.js' {
  declare module.exports: $Exports<'react-table/src/hooks/tests/useTable.test'>;
}
declare module 'react-table/src/hooks/useTable.js' {
  declare module.exports: $Exports<'react-table/src/hooks/useTable'>;
}
declare module 'react-table/src/index.js' {
  declare module.exports: $Exports<'react-table/src/index'>;
}
declare module 'react-table/src/plugin-hooks/tests/useAbsoluteLayout.test.js' {
  declare module.exports: $Exports<'react-table/src/plugin-hooks/tests/useAbsoluteLayout.test'>;
}
declare module 'react-table/src/plugin-hooks/tests/useBlockLayout.test.js' {
  declare module.exports: $Exports<'react-table/src/plugin-hooks/tests/useBlockLayout.test'>;
}
declare module 'react-table/src/plugin-hooks/tests/useExpanded.test.js' {
  declare module.exports: $Exports<'react-table/src/plugin-hooks/tests/useExpanded.test'>;
}
declare module 'react-table/src/plugin-hooks/tests/useFilters.test.js' {
  declare module.exports: $Exports<'react-table/src/plugin-hooks/tests/useFilters.test'>;
}
declare module 'react-table/src/plugin-hooks/tests/useGroupBy.test.js' {
  declare module.exports: $Exports<'react-table/src/plugin-hooks/tests/useGroupBy.test'>;
}
declare module 'react-table/src/plugin-hooks/tests/usePagination.test.js' {
  declare module.exports: $Exports<'react-table/src/plugin-hooks/tests/usePagination.test'>;
}
declare module 'react-table/src/plugin-hooks/tests/useRowSelect.test.js' {
  declare module.exports: $Exports<'react-table/src/plugin-hooks/tests/useRowSelect.test'>;
}
declare module 'react-table/src/plugin-hooks/tests/useSortBy.test.js' {
  declare module.exports: $Exports<'react-table/src/plugin-hooks/tests/useSortBy.test'>;
}
declare module 'react-table/src/plugin-hooks/useAbsoluteLayout.js' {
  declare module.exports: $Exports<'react-table/src/plugin-hooks/useAbsoluteLayout'>;
}
declare module 'react-table/src/plugin-hooks/useBlockLayout.js' {
  declare module.exports: $Exports<'react-table/src/plugin-hooks/useBlockLayout'>;
}
declare module 'react-table/src/plugin-hooks/useColumnOrder.js' {
  declare module.exports: $Exports<'react-table/src/plugin-hooks/useColumnOrder'>;
}
declare module 'react-table/src/plugin-hooks/useExpanded.js' {
  declare module.exports: $Exports<'react-table/src/plugin-hooks/useExpanded'>;
}
declare module 'react-table/src/plugin-hooks/useFilters.js' {
  declare module.exports: $Exports<'react-table/src/plugin-hooks/useFilters'>;
}
declare module 'react-table/src/plugin-hooks/useGroupBy.js' {
  declare module.exports: $Exports<'react-table/src/plugin-hooks/useGroupBy'>;
}
declare module 'react-table/src/plugin-hooks/usePagination.js' {
  declare module.exports: $Exports<'react-table/src/plugin-hooks/usePagination'>;
}
declare module 'react-table/src/plugin-hooks/useResizeColumns.js' {
  declare module.exports: $Exports<'react-table/src/plugin-hooks/useResizeColumns'>;
}
declare module 'react-table/src/plugin-hooks/useRowSelect.js' {
  declare module.exports: $Exports<'react-table/src/plugin-hooks/useRowSelect'>;
}
declare module 'react-table/src/plugin-hooks/useRowState.js' {
  declare module.exports: $Exports<'react-table/src/plugin-hooks/useRowState'>;
}
declare module 'react-table/src/plugin-hooks/useSortBy.js' {
  declare module.exports: $Exports<'react-table/src/plugin-hooks/useSortBy'>;
}
declare module 'react-table/src/sortTypes.js' {
  declare module.exports: $Exports<'react-table/src/sortTypes'>;
}
declare module 'react-table/src/utility-hooks/useTokenPagination.js' {
  declare module.exports: $Exports<'react-table/src/utility-hooks/useTokenPagination'>;
}
declare module 'react-table/src/utils.js' {
  declare module.exports: $Exports<'react-table/src/utils'>;
}
