// flow-typed signature: 81f10a225bd86e3d7468c039041ea971
// flow-typed version: <<STUB>>/ui-kit_v0.1.0/flow_v0.107.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ui-kit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ui-kit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ui-kit/dist/build' {
  declare module.exports: any;
}

declare module 'ui-kit/flow-typed/npm/@babel/core_vx.x.x' {
  declare module.exports: any;
}

declare module 'ui-kit/flow-typed/npm/@babel/preset-env_vx.x.x' {
  declare module.exports: any;
}

declare module 'ui-kit/flow-typed/npm/@babel/preset-flow_vx.x.x' {
  declare module.exports: any;
}

declare module 'ui-kit/flow-typed/npm/@storybook/addon-actions_vx.x.x' {
  declare module.exports: any;
}

declare module 'ui-kit/flow-typed/npm/@storybook/addon-knobs_vx.x.x' {
  declare module.exports: any;
}

declare module 'ui-kit/flow-typed/npm/@storybook/addon-links_vx.x.x' {
  declare module.exports: any;
}

declare module 'ui-kit/flow-typed/npm/@storybook/addons_vx.x.x' {
  declare module.exports: any;
}

declare module 'ui-kit/flow-typed/npm/@storybook/react_v5.x.x' {
  declare module.exports: any;
}

declare module 'ui-kit/flow-typed/npm/autoprefixer_vx.x.x' {
  declare module.exports: any;
}

declare module 'ui-kit/flow-typed/npm/babel-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'ui-kit/flow-typed/npm/classnames_v2.x.x' {
  declare module.exports: any;
}

declare module 'ui-kit/flow-typed/npm/classnames_vx.x.x' {
  declare module.exports: any;
}

declare module 'ui-kit/flow-typed/npm/enzyme_v3.x.x' {
  declare module.exports: any;
}

declare module 'ui-kit/flow-typed/npm/enzyme-adapter-react-16_vx.x.x' {
  declare module.exports: any;
}

declare module 'ui-kit/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'ui-kit/flow-typed/npm/lodash.noop_vx.x.x' {
  declare module.exports: any;
}

declare module 'ui-kit/flow-typed/npm/mini-css-extract-plugin_vx.x.x' {
  declare module.exports: any;
}

declare module 'ui-kit/flow-typed/npm/postcss-flexbugs-fixes_vx.x.x' {
  declare module.exports: any;
}

declare module 'ui-kit/flow-typed/npm/postcss-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'ui-kit/flow-typed/npm/postcss-normalize_vx.x.x' {
  declare module.exports: any;
}

declare module 'ui-kit/flow-typed/npm/postcss-preset-env_vx.x.x' {
  declare module.exports: any;
}

declare module 'ui-kit/flow-typed/npm/postcss-scss_vx.x.x' {
  declare module.exports: any;
}

declare module 'ui-kit/flow-typed/npm/react-day-picker_vx.x.x' {
  declare module.exports: any;
}

declare module 'ui-kit/flow-typed/npm/react-router-dom_v5.x.x' {
  declare module.exports: any;
}

declare module 'ui-kit/flow-typed/npm/react-router-dynamic-breadcrumbs_vx.x.x' {
  declare module.exports: any;
}

declare module 'ui-kit/flow-typed/npm/sass-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'ui-kit/flow-typed/npm/webpack_v4.x.x' {
  declare module.exports: any;
}

declare module 'ui-kit/flow-typed/npm/webpack-cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'ui-kit/postcss.config' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Breadcrumbs/Breadcrumbs.stories' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Breadcrumbs/index' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Breadcrumbs/tests/index.test' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Button/Button' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Button/Button.stories' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Button/ButtonWithProgress' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Button/index' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Button/tests/index.test' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Button/types' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Checkbox/Checkbox.stories' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Checkbox/index' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Checkbox/tests/index.test' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Chip/Chips.stories' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Chip/index' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Chip/tests/index.test' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Combobox/Combobox.stories' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Combobox/index' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Combobox/tests/index.test' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Container/Container.stories' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Container/index' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Container/tests/index.test' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Datepicker/Datepicker.stories' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Datepicker/index' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Datepicker/tests/index.test' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Dropdown/Dropdown.stories' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Dropdown/index' {
  declare module.exports: any;
}

declare module 'ui-kit/src/ErrorText/ErrorText.stories' {
  declare module.exports: any;
}

declare module 'ui-kit/src/ErrorText/index' {
  declare module.exports: any;
}

declare module 'ui-kit/src/ErrorText/tests/index.test' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Headings/Headings.stories' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Headings/index' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Headings/tests/index.test' {
  declare module.exports: any;
}

declare module 'ui-kit/src/IconInput/IconInput.stories' {
  declare module.exports: any;
}

declare module 'ui-kit/src/IconInput/index' {
  declare module.exports: any;
}

declare module 'ui-kit/src/IconInput/tests/index.test' {
  declare module.exports: any;
}

declare module 'ui-kit/src/index' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Input/index' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Input/Input.stories' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Input/tests/index.test' {
  declare module.exports: any;
}

declare module 'ui-kit/src/LinkButton/index' {
  declare module.exports: any;
}

declare module 'ui-kit/src/LinkButton/LinkButton.stories' {
  declare module.exports: any;
}

declare module 'ui-kit/src/LinkButton/tests/index.test' {
  declare module.exports: any;
}

declare module 'ui-kit/src/LinkIconButton/index' {
  declare module.exports: any;
}

declare module 'ui-kit/src/LinkIconButton/LinkIconButton.stories' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Modal/index' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Modal/Modal' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Modal/Modal.stories' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Modal/ModalBody' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Modal/ModalFooter' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Modal/ModalHeader' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Navbar/index' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Navbar/Navbar.stories' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Navbar/tests/index.test' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Participants/index' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Participants/Participants.stories' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Participants/tests/index.test' {
  declare module.exports: any;
}

declare module 'ui-kit/src/PopoverButton/index' {
  declare module.exports: any;
}

declare module 'ui-kit/src/PopoverButton/PopoverButton.stories' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Radio/index' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Radio/Radio.stories' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Separator/index' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Separator/Separator.stories' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Separator/tests/index.test' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Spinner/index' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Spinner/Spinner.stories' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Spinner/tests/index.test' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Switcher/index' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Switcher/Switcher.stories' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Switcher/tests/index.test' {
  declare module.exports: any;
}

declare module 'ui-kit/src/TablePaginate/default' {
  declare module.exports: any;
}

declare module 'ui-kit/src/TablePaginate/index' {
  declare module.exports: any;
}

declare module 'ui-kit/src/TablePaginate/Paginate' {
  declare module.exports: any;
}

declare module 'ui-kit/src/TablePaginate/TablePaginate.stories' {
  declare module.exports: any;
}

declare module 'ui-kit/src/TablePaginate/tests/index.test' {
  declare module.exports: any;
}

declare module 'ui-kit/src/TablePaginate/types' {
  declare module.exports: any;
}

declare module 'ui-kit/src/TextArea/index' {
  declare module.exports: any;
}

declare module 'ui-kit/src/TextArea/TextArea.stories' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Toast/index' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Toast/tests/index.test' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Toast/Toast' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Toast/Toast.stories' {
  declare module.exports: any;
}

declare module 'ui-kit/src/Toast/ToastStatic' {
  declare module.exports: any;
}

declare module 'ui-kit/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ui-kit/dist/build.js' {
  declare module.exports: $Exports<'ui-kit/dist/build'>;
}
declare module 'ui-kit/flow-typed/npm/@babel/core_vx.x.x.js' {
  declare module.exports: $Exports<'ui-kit/flow-typed/npm/@babel/core_vx.x.x'>;
}
declare module 'ui-kit/flow-typed/npm/@babel/preset-env_vx.x.x.js' {
  declare module.exports: $Exports<'ui-kit/flow-typed/npm/@babel/preset-env_vx.x.x'>;
}
declare module 'ui-kit/flow-typed/npm/@babel/preset-flow_vx.x.x.js' {
  declare module.exports: $Exports<'ui-kit/flow-typed/npm/@babel/preset-flow_vx.x.x'>;
}
declare module 'ui-kit/flow-typed/npm/@storybook/addon-actions_vx.x.x.js' {
  declare module.exports: $Exports<'ui-kit/flow-typed/npm/@storybook/addon-actions_vx.x.x'>;
}
declare module 'ui-kit/flow-typed/npm/@storybook/addon-knobs_vx.x.x.js' {
  declare module.exports: $Exports<'ui-kit/flow-typed/npm/@storybook/addon-knobs_vx.x.x'>;
}
declare module 'ui-kit/flow-typed/npm/@storybook/addon-links_vx.x.x.js' {
  declare module.exports: $Exports<'ui-kit/flow-typed/npm/@storybook/addon-links_vx.x.x'>;
}
declare module 'ui-kit/flow-typed/npm/@storybook/addons_vx.x.x.js' {
  declare module.exports: $Exports<'ui-kit/flow-typed/npm/@storybook/addons_vx.x.x'>;
}
declare module 'ui-kit/flow-typed/npm/@storybook/react_v5.x.x.js' {
  declare module.exports: $Exports<'ui-kit/flow-typed/npm/@storybook/react_v5.x.x'>;
}
declare module 'ui-kit/flow-typed/npm/autoprefixer_vx.x.x.js' {
  declare module.exports: $Exports<'ui-kit/flow-typed/npm/autoprefixer_vx.x.x'>;
}
declare module 'ui-kit/flow-typed/npm/babel-loader_vx.x.x.js' {
  declare module.exports: $Exports<'ui-kit/flow-typed/npm/babel-loader_vx.x.x'>;
}
declare module 'ui-kit/flow-typed/npm/classnames_v2.x.x.js' {
  declare module.exports: $Exports<'ui-kit/flow-typed/npm/classnames_v2.x.x'>;
}
declare module 'ui-kit/flow-typed/npm/classnames_vx.x.x.js' {
  declare module.exports: $Exports<'ui-kit/flow-typed/npm/classnames_vx.x.x'>;
}
declare module 'ui-kit/flow-typed/npm/enzyme_v3.x.x.js' {
  declare module.exports: $Exports<'ui-kit/flow-typed/npm/enzyme_v3.x.x'>;
}
declare module 'ui-kit/flow-typed/npm/enzyme-adapter-react-16_vx.x.x.js' {
  declare module.exports: $Exports<'ui-kit/flow-typed/npm/enzyme-adapter-react-16_vx.x.x'>;
}
declare module 'ui-kit/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'ui-kit/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'ui-kit/flow-typed/npm/lodash.noop_vx.x.x.js' {
  declare module.exports: $Exports<'ui-kit/flow-typed/npm/lodash.noop_vx.x.x'>;
}
declare module 'ui-kit/flow-typed/npm/mini-css-extract-plugin_vx.x.x.js' {
  declare module.exports: $Exports<'ui-kit/flow-typed/npm/mini-css-extract-plugin_vx.x.x'>;
}
declare module 'ui-kit/flow-typed/npm/postcss-flexbugs-fixes_vx.x.x.js' {
  declare module.exports: $Exports<'ui-kit/flow-typed/npm/postcss-flexbugs-fixes_vx.x.x'>;
}
declare module 'ui-kit/flow-typed/npm/postcss-loader_vx.x.x.js' {
  declare module.exports: $Exports<'ui-kit/flow-typed/npm/postcss-loader_vx.x.x'>;
}
declare module 'ui-kit/flow-typed/npm/postcss-normalize_vx.x.x.js' {
  declare module.exports: $Exports<'ui-kit/flow-typed/npm/postcss-normalize_vx.x.x'>;
}
declare module 'ui-kit/flow-typed/npm/postcss-preset-env_vx.x.x.js' {
  declare module.exports: $Exports<'ui-kit/flow-typed/npm/postcss-preset-env_vx.x.x'>;
}
declare module 'ui-kit/flow-typed/npm/postcss-scss_vx.x.x.js' {
  declare module.exports: $Exports<'ui-kit/flow-typed/npm/postcss-scss_vx.x.x'>;
}
declare module 'ui-kit/flow-typed/npm/react-day-picker_vx.x.x.js' {
  declare module.exports: $Exports<'ui-kit/flow-typed/npm/react-day-picker_vx.x.x'>;
}
declare module 'ui-kit/flow-typed/npm/react-router-dom_v5.x.x.js' {
  declare module.exports: $Exports<'ui-kit/flow-typed/npm/react-router-dom_v5.x.x'>;
}
declare module 'ui-kit/flow-typed/npm/react-router-dynamic-breadcrumbs_vx.x.x.js' {
  declare module.exports: $Exports<'ui-kit/flow-typed/npm/react-router-dynamic-breadcrumbs_vx.x.x'>;
}
declare module 'ui-kit/flow-typed/npm/sass-loader_vx.x.x.js' {
  declare module.exports: $Exports<'ui-kit/flow-typed/npm/sass-loader_vx.x.x'>;
}
declare module 'ui-kit/flow-typed/npm/webpack_v4.x.x.js' {
  declare module.exports: $Exports<'ui-kit/flow-typed/npm/webpack_v4.x.x'>;
}
declare module 'ui-kit/flow-typed/npm/webpack-cli_vx.x.x.js' {
  declare module.exports: $Exports<'ui-kit/flow-typed/npm/webpack-cli_vx.x.x'>;
}
declare module 'ui-kit/postcss.config.js' {
  declare module.exports: $Exports<'ui-kit/postcss.config'>;
}
declare module 'ui-kit/src/Breadcrumbs/Breadcrumbs.stories.js' {
  declare module.exports: $Exports<'ui-kit/src/Breadcrumbs/Breadcrumbs.stories'>;
}
declare module 'ui-kit/src/Breadcrumbs/index.js' {
  declare module.exports: $Exports<'ui-kit/src/Breadcrumbs/index'>;
}
declare module 'ui-kit/src/Breadcrumbs/tests/index.test.js' {
  declare module.exports: $Exports<'ui-kit/src/Breadcrumbs/tests/index.test'>;
}
declare module 'ui-kit/src/Button/Button.js' {
  declare module.exports: $Exports<'ui-kit/src/Button/Button'>;
}
declare module 'ui-kit/src/Button/Button.stories.js' {
  declare module.exports: $Exports<'ui-kit/src/Button/Button.stories'>;
}
declare module 'ui-kit/src/Button/ButtonWithProgress.js' {
  declare module.exports: $Exports<'ui-kit/src/Button/ButtonWithProgress'>;
}
declare module 'ui-kit/src/Button/index.js' {
  declare module.exports: $Exports<'ui-kit/src/Button/index'>;
}
declare module 'ui-kit/src/Button/tests/index.test.js' {
  declare module.exports: $Exports<'ui-kit/src/Button/tests/index.test'>;
}
declare module 'ui-kit/src/Button/types.js' {
  declare module.exports: $Exports<'ui-kit/src/Button/types'>;
}
declare module 'ui-kit/src/Checkbox/Checkbox.stories.js' {
  declare module.exports: $Exports<'ui-kit/src/Checkbox/Checkbox.stories'>;
}
declare module 'ui-kit/src/Checkbox/index.js' {
  declare module.exports: $Exports<'ui-kit/src/Checkbox/index'>;
}
declare module 'ui-kit/src/Checkbox/tests/index.test.js' {
  declare module.exports: $Exports<'ui-kit/src/Checkbox/tests/index.test'>;
}
declare module 'ui-kit/src/Chip/Chips.stories.js' {
  declare module.exports: $Exports<'ui-kit/src/Chip/Chips.stories'>;
}
declare module 'ui-kit/src/Chip/index.js' {
  declare module.exports: $Exports<'ui-kit/src/Chip/index'>;
}
declare module 'ui-kit/src/Chip/tests/index.test.js' {
  declare module.exports: $Exports<'ui-kit/src/Chip/tests/index.test'>;
}
declare module 'ui-kit/src/Combobox/Combobox.stories.js' {
  declare module.exports: $Exports<'ui-kit/src/Combobox/Combobox.stories'>;
}
declare module 'ui-kit/src/Combobox/index.js' {
  declare module.exports: $Exports<'ui-kit/src/Combobox/index'>;
}
declare module 'ui-kit/src/Combobox/tests/index.test.js' {
  declare module.exports: $Exports<'ui-kit/src/Combobox/tests/index.test'>;
}
declare module 'ui-kit/src/Container/Container.stories.js' {
  declare module.exports: $Exports<'ui-kit/src/Container/Container.stories'>;
}
declare module 'ui-kit/src/Container/index.js' {
  declare module.exports: $Exports<'ui-kit/src/Container/index'>;
}
declare module 'ui-kit/src/Container/tests/index.test.js' {
  declare module.exports: $Exports<'ui-kit/src/Container/tests/index.test'>;
}
declare module 'ui-kit/src/Datepicker/Datepicker.stories.js' {
  declare module.exports: $Exports<'ui-kit/src/Datepicker/Datepicker.stories'>;
}
declare module 'ui-kit/src/Datepicker/index.js' {
  declare module.exports: $Exports<'ui-kit/src/Datepicker/index'>;
}
declare module 'ui-kit/src/Datepicker/tests/index.test.js' {
  declare module.exports: $Exports<'ui-kit/src/Datepicker/tests/index.test'>;
}
declare module 'ui-kit/src/Dropdown/Dropdown.stories.js' {
  declare module.exports: $Exports<'ui-kit/src/Dropdown/Dropdown.stories'>;
}
declare module 'ui-kit/src/Dropdown/index.js' {
  declare module.exports: $Exports<'ui-kit/src/Dropdown/index'>;
}
declare module 'ui-kit/src/ErrorText/ErrorText.stories.js' {
  declare module.exports: $Exports<'ui-kit/src/ErrorText/ErrorText.stories'>;
}
declare module 'ui-kit/src/ErrorText/index.js' {
  declare module.exports: $Exports<'ui-kit/src/ErrorText/index'>;
}
declare module 'ui-kit/src/ErrorText/tests/index.test.js' {
  declare module.exports: $Exports<'ui-kit/src/ErrorText/tests/index.test'>;
}
declare module 'ui-kit/src/Headings/Headings.stories.js' {
  declare module.exports: $Exports<'ui-kit/src/Headings/Headings.stories'>;
}
declare module 'ui-kit/src/Headings/index.js' {
  declare module.exports: $Exports<'ui-kit/src/Headings/index'>;
}
declare module 'ui-kit/src/Headings/tests/index.test.js' {
  declare module.exports: $Exports<'ui-kit/src/Headings/tests/index.test'>;
}
declare module 'ui-kit/src/IconInput/IconInput.stories.js' {
  declare module.exports: $Exports<'ui-kit/src/IconInput/IconInput.stories'>;
}
declare module 'ui-kit/src/IconInput/index.js' {
  declare module.exports: $Exports<'ui-kit/src/IconInput/index'>;
}
declare module 'ui-kit/src/IconInput/tests/index.test.js' {
  declare module.exports: $Exports<'ui-kit/src/IconInput/tests/index.test'>;
}
declare module 'ui-kit/src/index.js' {
  declare module.exports: $Exports<'ui-kit/src/index'>;
}
declare module 'ui-kit/src/Input/index.js' {
  declare module.exports: $Exports<'ui-kit/src/Input/index'>;
}
declare module 'ui-kit/src/Input/Input.stories.js' {
  declare module.exports: $Exports<'ui-kit/src/Input/Input.stories'>;
}
declare module 'ui-kit/src/Input/tests/index.test.js' {
  declare module.exports: $Exports<'ui-kit/src/Input/tests/index.test'>;
}
declare module 'ui-kit/src/LinkButton/index.js' {
  declare module.exports: $Exports<'ui-kit/src/LinkButton/index'>;
}
declare module 'ui-kit/src/LinkButton/LinkButton.stories.js' {
  declare module.exports: $Exports<'ui-kit/src/LinkButton/LinkButton.stories'>;
}
declare module 'ui-kit/src/LinkButton/tests/index.test.js' {
  declare module.exports: $Exports<'ui-kit/src/LinkButton/tests/index.test'>;
}
declare module 'ui-kit/src/LinkIconButton/index.js' {
  declare module.exports: $Exports<'ui-kit/src/LinkIconButton/index'>;
}
declare module 'ui-kit/src/LinkIconButton/LinkIconButton.stories.js' {
  declare module.exports: $Exports<'ui-kit/src/LinkIconButton/LinkIconButton.stories'>;
}
declare module 'ui-kit/src/Modal/index.js' {
  declare module.exports: $Exports<'ui-kit/src/Modal/index'>;
}
declare module 'ui-kit/src/Modal/Modal.js' {
  declare module.exports: $Exports<'ui-kit/src/Modal/Modal'>;
}
declare module 'ui-kit/src/Modal/Modal.stories.js' {
  declare module.exports: $Exports<'ui-kit/src/Modal/Modal.stories'>;
}
declare module 'ui-kit/src/Modal/ModalBody.js' {
  declare module.exports: $Exports<'ui-kit/src/Modal/ModalBody'>;
}
declare module 'ui-kit/src/Modal/ModalFooter.js' {
  declare module.exports: $Exports<'ui-kit/src/Modal/ModalFooter'>;
}
declare module 'ui-kit/src/Modal/ModalHeader.js' {
  declare module.exports: $Exports<'ui-kit/src/Modal/ModalHeader'>;
}
declare module 'ui-kit/src/Navbar/index.js' {
  declare module.exports: $Exports<'ui-kit/src/Navbar/index'>;
}
declare module 'ui-kit/src/Navbar/Navbar.stories.js' {
  declare module.exports: $Exports<'ui-kit/src/Navbar/Navbar.stories'>;
}
declare module 'ui-kit/src/Navbar/tests/index.test.js' {
  declare module.exports: $Exports<'ui-kit/src/Navbar/tests/index.test'>;
}
declare module 'ui-kit/src/Participants/index.js' {
  declare module.exports: $Exports<'ui-kit/src/Participants/index'>;
}
declare module 'ui-kit/src/Participants/Participants.stories.js' {
  declare module.exports: $Exports<'ui-kit/src/Participants/Participants.stories'>;
}
declare module 'ui-kit/src/Participants/tests/index.test.js' {
  declare module.exports: $Exports<'ui-kit/src/Participants/tests/index.test'>;
}
declare module 'ui-kit/src/PopoverButton/index.js' {
  declare module.exports: $Exports<'ui-kit/src/PopoverButton/index'>;
}
declare module 'ui-kit/src/PopoverButton/PopoverButton.stories.js' {
  declare module.exports: $Exports<'ui-kit/src/PopoverButton/PopoverButton.stories'>;
}
declare module 'ui-kit/src/Radio/index.js' {
  declare module.exports: $Exports<'ui-kit/src/Radio/index'>;
}
declare module 'ui-kit/src/Radio/Radio.stories.js' {
  declare module.exports: $Exports<'ui-kit/src/Radio/Radio.stories'>;
}
declare module 'ui-kit/src/Separator/index.js' {
  declare module.exports: $Exports<'ui-kit/src/Separator/index'>;
}
declare module 'ui-kit/src/Separator/Separator.stories.js' {
  declare module.exports: $Exports<'ui-kit/src/Separator/Separator.stories'>;
}
declare module 'ui-kit/src/Separator/tests/index.test.js' {
  declare module.exports: $Exports<'ui-kit/src/Separator/tests/index.test'>;
}
declare module 'ui-kit/src/Spinner/index.js' {
  declare module.exports: $Exports<'ui-kit/src/Spinner/index'>;
}
declare module 'ui-kit/src/Spinner/Spinner.stories.js' {
  declare module.exports: $Exports<'ui-kit/src/Spinner/Spinner.stories'>;
}
declare module 'ui-kit/src/Spinner/tests/index.test.js' {
  declare module.exports: $Exports<'ui-kit/src/Spinner/tests/index.test'>;
}
declare module 'ui-kit/src/Switcher/index.js' {
  declare module.exports: $Exports<'ui-kit/src/Switcher/index'>;
}
declare module 'ui-kit/src/Switcher/Switcher.stories.js' {
  declare module.exports: $Exports<'ui-kit/src/Switcher/Switcher.stories'>;
}
declare module 'ui-kit/src/Switcher/tests/index.test.js' {
  declare module.exports: $Exports<'ui-kit/src/Switcher/tests/index.test'>;
}
declare module 'ui-kit/src/TablePaginate/default.js' {
  declare module.exports: $Exports<'ui-kit/src/TablePaginate/default'>;
}
declare module 'ui-kit/src/TablePaginate/index.js' {
  declare module.exports: $Exports<'ui-kit/src/TablePaginate/index'>;
}
declare module 'ui-kit/src/TablePaginate/Paginate.js' {
  declare module.exports: $Exports<'ui-kit/src/TablePaginate/Paginate'>;
}
declare module 'ui-kit/src/TablePaginate/TablePaginate.stories.js' {
  declare module.exports: $Exports<'ui-kit/src/TablePaginate/TablePaginate.stories'>;
}
declare module 'ui-kit/src/TablePaginate/tests/index.test.js' {
  declare module.exports: $Exports<'ui-kit/src/TablePaginate/tests/index.test'>;
}
declare module 'ui-kit/src/TablePaginate/types.js' {
  declare module.exports: $Exports<'ui-kit/src/TablePaginate/types'>;
}
declare module 'ui-kit/src/TextArea/index.js' {
  declare module.exports: $Exports<'ui-kit/src/TextArea/index'>;
}
declare module 'ui-kit/src/TextArea/TextArea.stories.js' {
  declare module.exports: $Exports<'ui-kit/src/TextArea/TextArea.stories'>;
}
declare module 'ui-kit/src/Toast/index.js' {
  declare module.exports: $Exports<'ui-kit/src/Toast/index'>;
}
declare module 'ui-kit/src/Toast/tests/index.test.js' {
  declare module.exports: $Exports<'ui-kit/src/Toast/tests/index.test'>;
}
declare module 'ui-kit/src/Toast/Toast.js' {
  declare module.exports: $Exports<'ui-kit/src/Toast/Toast'>;
}
declare module 'ui-kit/src/Toast/Toast.stories.js' {
  declare module.exports: $Exports<'ui-kit/src/Toast/Toast.stories'>;
}
declare module 'ui-kit/src/Toast/ToastStatic.js' {
  declare module.exports: $Exports<'ui-kit/src/Toast/ToastStatic'>;
}
declare module 'ui-kit/webpack.config.js' {
  declare module.exports: $Exports<'ui-kit/webpack.config'>;
}
