const projectActionTypes = {
  SAVE_PROJECT: 'SAVE_PROJECT',
  // GET_ALL_PROJECTS: "GET_ALL_PROJECTS",
  EDIT_PROJECT: 'EDIT_PROJECT',

  GET_PROJECT_TYPES_REQUEST: 'GET_PROJECT_TYPES_REQUEST',
  GET_PROJECT_TYPES_FAIL: 'GET_PROJECT_TYPES_FAIL',
  GET_PROJECT_TYPES_SUCCESS: 'GET_PROJECT_TYPES_SUCCESS',

};

export default projectActionTypes;
