const milestoneActionTypes = {
  CREATE_MILESTONE: 'CREATE_MILESTONE',
  GET_ALL_MILESTONES: 'GET_ALL_MILESTONES',
  EDIT_MILESTONE: 'EDIT_MILESTONE',
  DELETE_MILESTONE: 'DELETE_MILESTONE',
};

export default milestoneActionTypes;
