export default {
  CREATE_TASK: 'SAVE_TASK',
  EDIT_TASK: 'EDIT_TASK',
  DELETE_TASK_BY_MILESTONE: 'DELETE_TASK_BY_MILESTONE',
  GET_TASKS_STATUSES_REQUEST: 'GET_TASKS_STATUSES_REQUEST',
  GET_TASKS_STATUSES_FAIL: 'GET_TASKS_STATUSES_FAIL',
  GET_TASKS_STATUSES_SUCCESS: 'GET_TASKS_STATUSES_SUCCESS',
};
